# 로지스틱회귀를 Neural Network 구조로 표현
 - 노드-연결선-노드
# Tensorflow keras 코드 사용 

----

## 로지스틱회귀 - Sequential
- 딥러닝 중 Sequential
- 분류는 accuracy로 평가
- 0.5 이상은 1로 예측

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import load_breast_cancer

In [3]:
cancer = load_breast_cancer()

x = cancer.data
y = cancer.target

x.shape, y.shape

# 노드 수 확인 = (30)

((569, 30), (569,))

In [8]:
# 청소
keras.backend.clear_session()

# 모델 선언
model = keras.models.Sequential()

# 모델 연결
model.add( keras.layers.Input(shape=(30,)) )
model.add( keras.layers.Dense(1, activation='sigmoid') )

# 모델 설정
model.compile(loss=keras.losses.binary_crossentropy,
              metrics=['accuracy'], optimizer='adam')

In [9]:
model.fit(x, y, epochs=10, verbose=1)

y_pred = model.predict(x)

# loss와 accuracy 확인

Epoch 1/10
18/18 [==============================] - 0s 1ms/step - loss: 72.0554 - accuracy: 0.6274
Epoch 2/10
18/18 [==============================] - 0s 1ms/step - loss: 53.7853 - accuracy: 0.6274
Epoch 3/10
18/18 [==============================] - 0s 1ms/step - loss: 35.0653 - accuracy: 0.6274
Epoch 4/10
18/18 [==============================] - 0s 1ms/step - loss: 17.1788 - accuracy: 0.6274
Epoch 5/10
18/18 [==============================] - 0s 1ms/step - loss: 2.8877 - accuracy: 0.7592
Epoch 6/10
18/18 [==============================] - 0s 1ms/step - loss: 1.5993 - accuracy: 0.7522
Epoch 7/10
18/18 [==============================] - 0s 1ms/step - loss: 1.3548 - accuracy: 0.7803
Epoch 8/10
18/18 [==============================] - 0s 1ms/step - loss: 1.3450 - accuracy: 0.7838
Epoch 9/10
18/18 [==============================] - 0s 1ms/step - loss: 1.2744 - accuracy: 0.7996
Epoch 10/10
18/18 [==============================] - 0s 1ms/step - loss: 1.2697 - accuracy: 0.7944


In [10]:
print(y[:5])
print(y_pred[:5].reshape(-1))

[0 0 0 0 0]
[9.6058208e-01 8.5080399e-20 5.6465402e-11 1.0000000e+00 1.1265929e-11]


## 로지스틱회귀 - Functional
- 딥러닝 중 Functional API
- Sequential, Functional 차이는 유연함 차이
- 모델 선언과 모델 연결의 순서 차이가 있음
- #모델연결에서 ol (il)를 주의

In [11]:
cancer = load_breast_cancer()

x = cancer.data
y = cancer.target

x.shape, y.shape

# 노드 수 확인 = (30)

((569, 30), (569,))

In [12]:
# 청소
keras.backend.clear_session()

# 모델 연결
il = keras.layers.Input(shape=(30,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# 모델 선언
model = keras.models.Model(il, ol)

# 모델 설정
model.compile(loss=keras.losses.binary_crossentropy,
              metrics=['accuracy'], optimizer='adam')

In [13]:
model.fit(x, y, epochs=10, verbose=1)

y_pred = model.predict(x)

Epoch 1/10
18/18 [==============================] - 0s 2ms/step - loss: 62.4368 - accuracy: 0.3726
Epoch 2/10
18/18 [==============================] - 0s 1ms/step - loss: 48.1419 - accuracy: 0.3726
Epoch 3/10
18/18 [==============================] - 0s 1ms/step - loss: 33.8425 - accuracy: 0.3726
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 19.5221 - accuracy: 0.3761
Epoch 5/10
18/18 [==============================] - 0s 1ms/step - loss: 7.0323 - accuracy: 0.4640
Epoch 6/10
18/18 [==============================] - 0s 1ms/step - loss: 3.8765 - accuracy: 0.6661
Epoch 7/10
18/18 [==============================] - 0s 1ms/step - loss: 3.5364 - accuracy: 0.6397
Epoch 8/10
18/18 [==============================] - 0s 1ms/step - loss: 3.4281 - accuracy: 0.6344
Epoch 9/10
18/18 [==============================] - 0s 1ms/step - loss: 3.3062 - accuracy: 0.6555
Epoch 10/10
18/18 [==============================] - 0s 1ms/step - loss: 3.1934 - accuracy: 0.6555


In [18]:
print(y[:5])
print(y_pred[:5].reshape(-1))

[0 0 0 0 0]
[1.0000000e+00 5.5686819e-13 3.2080393e-13 1.0000000e+00 3.8285664e-24]


In [17]:
model.summary()

# 30 + 1 -> 1 : bias

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________
