#### y(target)이 3가지 이상일 때, 멀티클래스 사용
#### y를 가변수화하여 사용

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

x = iris.data
y = iris.target

x.shape, y.shape

((150, 4), (150,))

In [5]:
y

# y가 0,1,2 로 범주형임.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
# one-hot encoding

from tensorflow.keras.utils import to_categorical

In [10]:
y = to_categorical(y,3)

In [11]:
x.shape, y.shape

((150, 4), (150, 3))

### 멀티클래스 - Sequential API
- activation='softmax'
- loss=keras.losses.categorical_crossentropy

In [13]:
##########
# 모델링 #
##########

# 모델 청소
keras.backend.clear_session()

# 모델 선언
model = keras.models.Sequential()

# 모델 연결
model.add( keras.layers.Input(shape=(4,)) )
model.add( keras.layers.Dense(3, activation='softmax'))

# 모델 설정
model.compile(loss=keras.losses.categorical_crossentropy,
              metrics=['accuracy'], optimizer='adam')

In [14]:
# 모델 학습
model.fit(x, y, epochs=10, verbose=1)

# 모델 예측
y_pred = model.predict(x)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 2.6046 - accuracy: 0.6600
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 2.5377 - accuracy: 0.6600
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 2.4710 - accuracy: 0.6600
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 2.4070 - accuracy: 0.6667
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 2.3436 - accuracy: 0.6667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 2.2806 - accuracy: 0.6667
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 2.2220 - accuracy: 0.6667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 2.1610 - accuracy: 0.6667
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 2.1035 - accuracy: 0.6667
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 2.0458 - accuracy: 0.6667


In [16]:
print(y[:5])
print(y_pred[:5])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[0.8378978  0.10745277 0.05464936]
 [0.7473559  0.19047153 0.06217257]
 [0.8072579  0.12692693 0.06581526]
 [0.7587474  0.1679467  0.07330588]
 [0.8527549  0.09086911 0.05637594]]


### 멀티클래스 - Functional API
- 

In [17]:
x.shape, y.shape

((150, 4), (150, 3))

In [18]:
##########
# 모델링 #
##########

# 청소
keras.backend.clear_session()

# 모델 연결
il = keras.layers.Input(shape=(4,))
ol = keras.layers.Dense(3, activation='softmax')(il)

# 모델 선언
model = keras.models.Model(il, ol)

# 모델 설정
model.compile(loss=keras.losses.categorical_crossentropy,
              metrics=['accuracy'], optimizer='adam')

In [19]:
model.fit(x, y, epochs=10, verbose=1)

y_pred = model.predict(x)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 3.8029 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 3.7188 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 3.6377 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 3.5565 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 3.4747 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 3.3958 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 3.3165 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 3.2398 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 3.1614 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 3.0863 - accuracy: 0.3333


In [20]:
print(y[:5])
print(y_pred[:5])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[0.00291924 0.18504131 0.81203943]
 [0.00316198 0.20483896 0.7919991 ]
 [0.00441815 0.2043457  0.79123616]
 [0.00384246 0.18368417 0.81247336]
 [0.0032717  0.17919101 0.8175373 ]]


In [21]:
model.summary()

# (4+1)*3 = 15
# 1 : bias(절편)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
